# Generated by Django 5.2.11 on 2026-03-05 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('blood_group', models.CharField(max_length=3)),
                ('urgency_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('critical', 'Critical')], max_length=10)),
                ('location', models.TextField()),
                ('required_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending AI Match'), ('matching', 'Finding Donors'), ('fulfilled', 'Fulfilled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AIAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_decision_data', models.JSONField(help_text='Stores the AI matching logic/scores')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('blood_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blood.bloodrequest')),
            ],
        ),
        migrations.CreateModel(
            name='DonationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('missed', 'Missed')], max_length=20)),
                ('trust_points_awarded', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('blood_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blood.bloodrequest')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
