# Generated by Django 5.2.11 on 2026-03-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_institutionalprofile_organization_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='disease_conditions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
